apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: sonar-provider-secret
type: Opaque
stringData:
  credentials: "XXX"
---
apiVersion: sonar.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: sonar
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: sonar-provider-secret
      key: credentials
